### ISSUE TITLE
ModuleNotFoundError: No module named 'gretel_helpers'

### ISSUE THREAD

**Issue by shadiakiki1986** [gretelai/gretel-blueprints#29]
I got this error while trying out your blueprint for creating synthetic data ([link](https://github.com/gretelai/gretel-blueprints/blob/master/gretel/create_synthetic_data_from_csv_or_df/blueprint.ipynb)). I'm not sure if the code is out-of-date or if I'm missing a package, but I already have `gretel-client gretel-synthetics pandas`.

Update: `gretel-synthetics version: 0.15.5`, `gretel-client Version: 0.7.11`

**Comment by johntmyers** [comment]
@shadiakiki1986 did you run the cell that installs the helpers? you need a Gretel API key:

```
# Load your Gretel API key. You can acquire this from the Gretel Console 
# @ https://console.gretel.cloud

import pandas as pd
from gretel_client import get_cloud_client

pd.set_option('max_colwidth', None)

client = get_cloud_client(prefix="api", api_key="prompt")
client.install_packages()
```

**Comment by shadiakiki1986** [comment]
No I hadn't. It works now. Is there a way to see what that installs? It looks like this installs packages from gretel cloud rather than pypi?

**Comment by shadiakiki1986** [comment]
Also, where is the documentation for `SyntheticDataBundle`? I'm getting an error asking me to reduce `character_coverage`, but I'm not sure what valid values are for that

**Comment by johntmyers** [comment]
The docs are embedded into the class, you can usually reference them via: "SyntheticDataBundle?" in a Notebook cell. 

The error you are getting seems like it's from our lower level open source package. Can you provide a full traceback?

**Comment by shadiakiki1986** [comment]
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-133-c72315b99576> in <module>()
----> 1 model.train()

7 frames
/usr/local/lib/python3.7/dist-packages/gretel_helpers/synthetics.py in train(self)
    371         if self.read_only:
    372             raise RuntimeError("Cannot train in read-only mode")
--> 373         self.synthetic_batches.train_all_batches()
    374 
    375     def generate(

/usr/local/lib/python3.7/dist-packages/gretel_synthetics/batch.py in train_all_batches(self)
    833             raise RuntimeError("Method cannot be used in read-only mode")
    834         for idx in self.batches.keys():
--> 835             self.train_batch(idx)
    836 
    837     def set_batch_validator(self, batch_idx: int, validator: Callable):

/usr/local/lib/python3.7/dist-packages/gretel_synthetics/batch.py in train_batch(self, batch_idx)
    824             raise RuntimeError("Method cannot be used in read-only mode")
    825         try:
--> 826             train(self.batches[batch_idx].config, _tokenizer)
    827         except KeyError:
    828             raise ValueError("batch_idx is invalid")

/usr/local/lib/python3.7/dist-packages/gretel_synthetics/train.py in train(store, tokenizer_trainer)
     81         tokenizer_trainer = _create_default_tokenizer(store)
     82     tokenizer_trainer.create_annotated_training_data()
---> 83     tokenizer_trainer.train()
     84     tokenizer = tokenizer_from_model_dir(store.checkpoint_dir)
     85     params = TrainingParams(

/usr/local/lib/python3.7/dist-packages/gretel_synthetics/tokenizers.py in train(self)
    159         located in the model directory specified by the ``config`` object
    160         """
--> 161         self._train()
    162         settings = self._get_save_settings()
    163         self._save_settings(settings)

/usr/local/lib/python3.7/dist-packages/gretel_synthetics/tokenizers.py in _train(self)
    445             input_sentence_size=self.pretrain_sentence_count,
    446             shuffle_input_sentence=True,
--> 447             character_coverage=self.character_coverage
    448         )
    449 

/usr/local/lib/python3.7/dist-packages/sentencepiece.py in Train(arg, **kwargs)
    439           return SentencePieceTrainer._TrainFromMap2(new_kwargs, sentence_iterator)
    440         else:
--> 441           return SentencePieceTrainer._TrainFromMap(new_kwargs)
    442 
    443       return None

/usr/local/lib/python3.7/dist-packages/sentencepiece.py in _TrainFromMap(args)
    384     @staticmethod
    385     def _TrainFromMap(args):
--> 386         return _sentencepiece.SentencePieceTrainer__TrainFromMap(args)
    387 
    388     @staticmethod

RuntimeError: Internal: /sentencepiece/src/trainer_interface.cc(513) [(static_cast<int>(required_chars_.size() + meta_pieces_.size())) <= (trainer_spec_.vocab_size())] Vocabulary size is smaller than required_chars. 7 vs 10. Increase vocab_size or decrease character_coverage with --character_coverage option.
```

**Comment by johntmyers** [comment]
What does your dataset look like? Is it sparse data or numerical, etc?

**Comment by shadiakiki1986** [comment]
A single column of 7 grades, `a,b,c,d,e,f,g,h`. I got it working with `config_template={..., "vocab_size": 10, "character_coverage": 0.98, ...}`

**Comment by johntmyers** [comment]
Ok. You can also try a vocab size bc of 0 which will switch to using a char by char tokenizer which can work better for less dynamic data. 

Also you could try decreasing the learning rate to .001 or so.

**Comment by shadiakiki1986** [comment]
Got it. How can I set the learning rate? `SyntheticDataBundle?` just gives out the below, so I'm unsure where to set it

```
Init signature: SyntheticDataBundle(*args, **kwargs)
Docstring:     
Class used to automate the generation of synthetic data with optional
automated header clustering and data validation
File:           /usr/local/lib/python3.7/dist-packages/gretel_helpers/synthetics.py
Type:           type
```

**Comment by johntmyers** [comment]
So the `config_template` dictionary can actually be all of the params that are available to the underlying Synthetic configuration from our open source: https://gretel-synthetics.readthedocs.io/en/stable/api/config.html#gretel_synthetics.config.TensorFlowConfig

You'll recognize `vocab_size`, `character_coverage` from being there.

Also, we are releasing some parameters that are optimal for various data source characteristics: https://github.com/gretelai/gretel-blueprints/tree/main/config_templates/gretel/synthetics -- you can look at the `params` object in the YAML and those values can also map to the `config_template` in the Blueprint.

We'll actually be releasing a blog on this shortly as we will be deprecating the the `SyntheticDataBundle` over the next 5-6 months and releasing a CLI tool that simply takes a config file and uses a REST API to schedule work to be done. This way multiple things can be trained in parallel, etc easily without having to rely on Notebooks exclusively.
