### ISSUE TITLE
CHECKPOINT_DIR Issue

### ISSUE THREAD

**Issue by erinkhoo** [gretelai/gretel-blueprints#33]
Getting a KeyError on account of "![Screenshot 2021-05-31 at 10 34 36](https://user-images.githubusercontent.com/866947/120175040-b1466780-c1fd-11eb-8f94-35736e050cd9.png)"

Can't access the path checkpoint_dir = str(Path.cwd() / "checkpoints-synthetics")

**Comment by johntmyers** [comment]
Hi. @erinkhoo can you share the code cell you have for creating the config template dict?

You may need to do a:

`config_template["checkpoint_dir"] = checkpoint_dir`


After creating the template dict.

**Comment by johntmyers** [comment]
@Ab-Abdurrahman I thought that's what was patched by this PR https://github.com/gretelai/gretel-blueprints/pull/35

**Comment by Ab-Abdurrahman** [comment]
@johntmyers I see from the PR. Sorry, I am using the Colab notebook from https://console.gretel.cloud/ for my work I think it is not updated from there.
