### ISSUE TITLE
Minimum training samples for 'create_synthetic_data_from_csv_or_df'

### ISSUE THREAD

**Issue by Ab-Abdurrahman** [gretelai/gretel-blueprints#36]
Hi! thanks for the repo, May I ask what is the minimum number of training samples required for creating synthetic_data_from_csv_dataframe? My CSV had less than 100 samples and i received an error `'RuntimeError: Model training failed. Your training data may have too few records in it. Please try increasing your training rows and try again'` when running the cell  `model.train()` from a create_synthetic_data_from_csv_or_df notebook.

**Comment by johntmyers** [comment]
Generally we recommend over a 1000. But really depends on the composition of the data. 

You may want to try the "low record count" config template to see if that works. You can reference the template directly in the Notebook instead of using the "default" template.

**Comment by Ab-Abdurrahman** [comment]
Thanks,@johntmyers, I have tried to use the `low-record-count` configuration but there is no synthetic data generated in my CSV. Please advise if there is anything I can adjust to get the desired output. My dataset has 70 rows with 7 columns

**Comment by johntmyers** [comment]
That is probably just too little of an amount of data. You might try oversampling by repeating your rows 5x, 10x etc. If you do this be sure to shuffle the rows. At this point though there could be an increased chance of repeating records during generation.

**Comment by Ab-Abdurrahman** [comment]
Thanks, @johntmyers I was able to generate the data after replicating and shuffling rows as suggested using a low-record-count.

**Comment by zredlined** [comment]
@Ab-Abdurrahman Glad to hear it works. Another alternative could be to drop the batch_size to 1, and the vocab_size to 0 (this means character-based vocab) before training, which shouldn't require you to repeat the dataset rows. Hope that helps!

You can see an example configuration for low record counts: https://github.com/gretelai/gretel-blueprints/blob/main/config_templates/gretel/synthetics/low-record-count.yml

**Comment by Ab-Abdurrahman** [comment]
Thanks @zredlined, will check this out and let you know.
