### ISSUE TITLE
Model doesn't capture latitude/longitude properly even though accuracy is high.

### ISSUE THREAD

**Issue by 9harshit** [gretelai/gretel-blueprints#39]
I am trying to generate synthetic lat/long data.
Table : user_id, timestamp, latitude and longitude.

I though accuracy is 80 percent the results are not useable at all.
<img width="1061" alt="Screen Shot 2021-06-22 at 3 32 29 PM" src="https://user-images.githubusercontent.com/43147421/122906091-68eb1700-d36f-11eb-8d15-00e5a0610d5f.png">

## Code 
train_data has 5442 rows with 10 unique user_id.

`config_template = {`
    `"epochs": 1000,`
    `"early_stopping": True,`
    `"vocab_size": 200000,`
    `"reset_states": True, `
    `"checkpoint_dir" : "/content/sample_data/check2/",`
  `  "overwrite": True`
`}`

`from gretel_helpers.series_models import TimeseriesModel`
`model = TimeseriesModel(`
   ` training_df=test_data,`
    `time_column="ts",`
   ` trend_columns = ['latitude', 'longitude'],`
  `  other_seed_columns=["user_id"],`
 `   synthetic_config=config_template)`
`model.train()`
`synthetic_df= model.generate().df`

<img width="740" alt="Screen Shot 2021-06-22 at 3 38 12 PM" src="https://user-images.githubusercontent.com/43147421/122906514-dd25ba80-d36f-11eb-8973-464f6591a44c.png">

Standard deviation is too much in synthetic data 

Should I train more increase dataset size to get better results?

# Red is synthetic data, blue is real

<img width="577" alt="Screen Shot 2021-06-22 at 3 32 22 PM" src="https://user-images.githubusercontent.com/43147421/122905786-2590a880-d36f-11eb-8382-4e18773e4c20.png">
<img width="402" alt="Screen Shot 2021-06-22 at 3 32 15 PM" src="https://user-images.githubusercontent.com/43147421/122905814-2de8e380-d36f-11eb-9a2c-9abd1cc23ddd.png">

**Comment by johntmyers** [comment]
Hi there - there's a few things you can try here:

1) Can you reduce the precision of the floating point numbers in the training data? The lower the better, for lat/lon can you do 3 or 4 decimals precision?

2) There's some config changes you can try to better work with this type of data (taken from[ this config template](https://github.com/gretelai/gretel-blueprints/blob/main/config_templates/gretel/synthetics/low-record-count.yml)):

- `batch_size`: 1
- `vocab_size`: 0
- `learning_rate`: .001

Let us know if this does any better!

**Comment by zredlined** [comment]
@9harshit try removing the latitude and longitude from your trend columns in the TimeseriesModel. When you specify those values as trend_columns, the model treats them as paths that would change over time (e.g. imagine if you're trying to recreate a path of latitude/longitude points taken by a fitness tracker), and not discrete points. 

If you remove the `trend_columns` from your config like below, it should work for you. Best of luck!

E.g.

```
from gretel_helpers.series_models import TimeseriesModel
model = TimeseriesModel(
training_df=test_data,
time_column="ts",
# REMOVE THIS trend_columns = ['latitude', 'longitude'],
other_seed_columns=["user_id"],
synthetic_config=config_template)
model.train()
synthetic_df= model.generate().df
```

**Comment by 9harshit** [comment]
@zredlined if I remove trend_column following error is generated :
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-96-6efe8ace7e73> in <module>()
     14     # trend_columns = ['latitude', 'longitude'],
     15     other_seed_columns=["user_id"],
---> 16     synthetic_config=config_template)
     17 model.train()
     18 synthetic_df= model.generate().df

TypeError: __init__() missing 1 required keyword-only argument: 'trend_columns'

**Comment by zredlined** [comment]
@9harshit My bad- the TimeseriesModel requires a trend column. If there isn't one, you'll want to go with the SeriesModel instead. I have updated the comment above. Hopefully this works for you!

**Comment by 9harshit** [comment]
Ya, thank you for the suggestions. also with Series Model the code you suggested had this error:

`RuntimeError: For this training data, auto_seed_corr is setting *all* possible columns to be seed columns. Which cannot be used for training a synthetic model. You will need to disable auto_seed_corr then try again.`

 changing auto_seed_corr to False, removed the error.
 
Will let you know if the suggestions worked or not. Please keep the issue open.

Thankyou

**Comment by 9harshit** [comment]
> Hi there - there's a few things you can try here:
> 
> 1. Can you reduce the precision of the floating point numbers in the training data? The lower the better, for lat/lon can you do 3 or 4 decimals precision?
> 2. There's some config changes you can try to better work with this type of data (taken from[ this config template](https://github.com/gretelai/gretel-blueprints/blob/main/config_templates/gretel/synthetics/low-record-count.yml)):
> 
> * `batch_size`: 1
> * `vocab_size`: 0
> * `learning_rate`: .001
> 
> Let us know if this does any better!

hi, config that you suggested doesn't work. it does not generate any valid rows only invalid rows

**Comment by 9harshit** [comment]
> @9harshit The time-series model expects a trend component to change, as you don't have any trending components in your dataset the best option for you is to use the SeriesModel and seed with your timestamps and user_id. Here's an example notebook: https://github.com/gretelai/gretel-blueprints/blob/master/gretel/create_synthetic_data_smart_seeding/blueprint.ipynb. For you, it would look something like this.
> 
> E.g.
> 
> ```
> from gretel_helpers.series_models import SeriesModel
> seed_columns = ["timestamp", "user_id"]
> 
> model = SeriesModel(
>     training_df=training_df,
>     seed_columns=seed_columns,
>     synthetic_config=config_template,
>     auto_seed_corr=True
> )
> 
> model.train()
> model.generate(max_invalid=1e5)
> 
> synthetic_df = model.df
> model.generate_report()
> ```
> 
> Hope this helps!

hi @zredlined Series model is producing exact carbon copy of my original dataset instead of producing new value with same distribution

**Comment by johntmyers** [comment]
Can you share the training dataset?

**Comment by 9harshit** [comment]
Sure
1. My dataset has 14 lakh users but currently I am only testing with 10 users:

This dataset has all the points recorded for 10 users : https://drive.google.com/file/d/1--DlYy1AslF1mQJ6zlcgTshCD22NKVH9/view?usp=sharing

2. This has 10000 random samples from the entire dataset :

https://drive.google.com/file/d/1--DlYy1AslF1mQJ6zlcgTshCD22NKVH9/view?usp=sharing

Let me know if you find the solution

**Comment by johntmyers** [comment]
Thanks. I forgot to ask for your notebook too

**Comment by 9harshit** [comment]
Time series code : https://colab.research.google.com/drive/1DRLlE9J5vX9Fm8RidHbLvZTgtnPEdTqv?usp=sharing
Series code : https://colab.research.google.com/drive/1S-q3eSjz2SYdoL-xO5ea8s2ANGAvK6Ae?usp=sharing
Bundle code : https://colab.research.google.com/drive/1fXmq698ZvDOywyHPuLM-P0qbODsbITAD?usp=sharing

**Comment by johntmyers** [comment]
So if you want to generate new user IDs along with locations, then I think you may want to use the "Bundle code". Both of the other notebooks will expect existing values to be provided. Within your "Bundle code" notebook, if you want to keep generating records or generate more records than the source dataset, then you can update your generate command to be:

```
bundle.generate(num_lines=10000)
```

Where `num_lines` is the number of records you want to generate.

When I look at the data for the points recorded for 10 users (which I think is what you are using in your notebooks) there is a lot of repeated data which is making it difficult to synthesize new unique records. I will check in with the team here to see what options there might be to create more varied synthetic data, if possible.

**Comment by 9harshit** [comment]
Hi @johntmyers  thanks for looking into my code. Different user may have repeated pings in the same location but timestamp is different also vice versa. And I want to replicate that too. that same user has multiple pings on different day and so on. 
Please do reach out to me, if you find some better solution.
Thanks

**Comment by johntmyers** [comment]
@9harshit Please try updating to the latest blueprint and reinstall to the latest SDK using the `client.install_packages()` command from the top cells: https://github.com/gretelai/gretel-blueprints/blob/master/gretel/create_synthetic_data_smart_seeding/blueprint.ipynb

I just tried using the numeric data template (https://github.com/gretelai/gretel-blueprints/blob/master/gretel/create_synthetic_data_smart_seeding/blueprint.ipynb) and this is what I'm getting from `df.describe()` from the synthetic data:

```
            user_id     latitude    longitude
count  4.999000e+03  5000.000000  5000.000000
mean   6.483237e+18    12.968617    77.621721
std    2.363052e+18     0.068199     0.043741
min    8.487040e+17    12.870000    77.532000
25%    6.325305e+18    12.907000    77.589000
50%    6.325305e+18    12.948000    77.632000
75%    8.993374e+18    13.034000    77.633000
max    9.014490e+18    13.110000    77.717000
```

**Comment by 9harshit** [comment]
Hi @johntmyers my model is working with new config, will analyze my results to see the performance that whether is recreating the distribution or just creating copy of the original data. Will share my results here.
Thanks

**Comment by zredlined** [comment]
Hey @9harshit just checking to see how your model is performing and if we can close out this ticket. Any feedback or results would be awesome, thanks!

**Comment by 9harshit** [comment]
Hey, @zredlined I did ran the file with new config, but didn't get a chance to do detailed analysis on it. One thing it did observe was for the Datetime column the model produces values that are not real (Example 31/02/2021 30:23:34) something like this. Same goes for float value and latitude and longitude column it produces numbers with more than one "."

**Comment by zredlined** [comment]
@9harshit Hmm, the lat/lon example sounds like a bug. Our validators should catch invalid float values in lat/lon columns automatically. Happy to chat about this anytime- we'd probably need to see an example of your dataset. Feel free to ping us on slack at https://gretel.ai/slackinvite.

Re: the datetime field, we probably need to create a validator for this. One possible way to address this in the meantime could be to convert the datetime fields to epochs (integer seconds/milliseconds since 1970).

**Comment by 9harshit** [comment]
that would be great @zredlined
